
name: Flask API CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: |
        curl -X POST \ 
        -H "Authorization: Bearer $RENDER_API_KEY" \ 
        -H "Content-Type: application/json" \ 
        -d '{"serviceId": "YOUR_SERVICE_ID", "clearCache": true}' \ 
        https://api.render.com/v1/services/SERVICE_ID/deploys
